# Copyright Altran Netherlands B.V

project: mde-skeleton
language: Java
code_location:
  source:
    - ./features/
    - ./products/
    - ./plugins/
    - ./releng/
  test:
    - ./tests/
artifact_repository_url: "https://nexus.acidspace.nl/repository/{}/{}{}"

build:
  binaries:
    platform: Maven
    precondition:
      - OutputDirectoryExists
      - OutputDirectoryIsEmpty
    postcondition:
      - OutputDirectoryIsNotEmpty
    parameters:
      output: ./reports/build/binaries
      build_settings_path: ./settings.xml
      build_pom_path: ./pom.xml

release:
  binaries:
    platform: P2
    precondition:
      - VersionDetermined
      - OutputDirectoryExists
      - OutputDirectoryIsEmpty
    postcondition:
      - OutputDirectoryIsNotEmpty
    parameters:
      repository: MDEAssets
      repository_path: mde-skeleton
      repository_project: ./products/com.altran.ec.mde.skeleton.package.product
      output: ./reports/release/binaries
