# Copyright Altran Netherlands B.V

project: mde-skeleton
language: Java
default_branch: "develop"
code_location:
  source:
    - ./features/
    - ./products/
    - ./plugins/
    - ./releng/
  test:
    - ./tests/
artifact_repository_url: "https://nexus.acidspace.nl/repository/{}/{}{}"

build:
  binaries:
    platform: Maven
    precondition:
      - OutputDirectoryExists
      - OutputDirectoryIsEmpty
    postcondition:
      - OutputDirectoryIsNotEmpty
    parameters:
      output: ./reports/build/binaries
      build_settings_path: ./settings.xml
      build_pom_path: ./pom.xml

test:
  units:
    platform: Maven
    precondition:
      - OutputDirectoryExists
      - OutputDirectoryIsEmpty
    postcondition:
      - OutputDirectoryIsNotEmpty
    parameters:
      output: ./reports/test/units
      test_settings_path: ./settings.xml
      test_pom_path: ./pom.xml
      index: test-units
