image: registry.acidspace.nl/acid/container/maven:1.1.0

variables:
  # Cache downloaded dependencies and plugins between builds
  MAVEN_REPO: '.m2/repository'
  MAVEN_OPTS: '-Dmaven.repo.local=$MAVEN_REPO -Xmx2048m'

cache:
  key: '$CI_JOB_NAME'
  paths:
    - '$MAVEN_REPO'

stages:
  - build

Build maven projects:
  stage: build
  tags:
    - linux_docker
  before_script:
    - 'echo "${MAVEN_REPO}: found $(find $MAVEN_REPO -type f 2>/dev/null | wc -l) matching files"'
    - 'chmod +x build.sh'
  script:
    - './build.sh'
  artifacts:
    when: always
    paths:
      - 'products/*/target/*.zip'
    reports:
      junit: 'tests/*/target/surefire-reports/*.xml'
