image: registry.acidspace.nl/acid/container/maven:1.0.0

stages:
  - build

Build maven projects:
  stage: build
  tags:
    - linux_docker
  script:
    - echo Building $CI_COMMIT_REF_NAME $CI_COMMIT_TAG...
