/**
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.generator;

import org.eclipse.xtext.example.fowlerdsl.generator.StatemachinePolviGenerator;
import org.espilce.polvi.emf.generator.xtext.PolviDelegateGenerator;

@SuppressWarnings("all")
public class StatemachinePolviDelegateGenerator extends PolviDelegateGenerator {
  public StatemachinePolviDelegateGenerator() {
    super(new StatemachinePolviGenerator());
  }
}
