/*
 * generated by Xtext
 */
package org.eclipse.xtext.example.fowlerdsl.generator

import org.espilce.polvi.emf.generator.xtext.PolviDelegateGenerator

class StatemachinePolviDelegateGenerator extends PolviDelegateGenerator {
  new() {
    super(new StatemachinePolviGenerator())
  }
}
