include::_attributes.adoc[]

[[using-mde-assets]]
== Using MDE Assets

This section acts as a quick reference guide on using MDE Assets in an MDE solution.
The focus is mainly on the integration part and for more information on the usage of an particular MDE Asset, please read its user, developer or programmer guide.

NOTE: For an MDE solution, an MDE Asset is a third-party-product and as such the general guidelines as documented in <<using-3pp>> should be followed when using an MDE Asset. 

=== EcoreDoc

WARNING: TODO

=== Espilce Commons

WARNING: TODO

=== Espilce Periksa

To start using Espilce Periksa, first it should be added to the the target platform, see the code snippet below.

.Adding Espilce Periksa to the link:{giturl}/releng/com.altran.ec.mde.skeleton.target/com.altran.ec.mde.skeleton.target.tpd[target-platform.tpd^]
[source,tpd]
----
include::{gitdir}/releng/com.altran.ec.mde.skeleton.target/com.altran.ec.mde.skeleton.target.tpd[tags=doc-espilce-periksa]
----

Then you can start writing the required validations.
The quickest way to create validations using Espilce Periksa is to create a class containing static methods that are annotated with the `@Check` annotation.
The first argument of the method is the model element to validate and the second argument injects the validation context as provided by Espilce Periksa.
For more information, please read the https://ec-mde.pages.acidspace.nl/espilce-periksa/#programmers-guide[Espilce Periksa programmer guide]. +
The example below adds a duplicate value error-validation for command names to the Fowler state-machine DSL Xtext example, and an info-validation for state names to start with a capital.

NOTE: Using the `@Check` annotation requires a bundle dependency of `org.espilce.periksa.validation`.

.Writing validations in link:{giturl}/plugins/com.altran.ec.mde.skeleton.espilce.periksa/src/com/altran/ec/mde/skeleton/espilce/periksa/StatemachineValidations.java[StatemachineValidations.java^] using Espilce Periksa
[source,java]
----
include::{gitdir}/plugins/com.altran.ec.mde.skeleton.espilce.periksa/src/com/altran/ec/mde/skeleton/espilce/periksa/StatemachineValidations.java[tag=doc-espilce-periksa]
----

<1> The `@Check` annotation registers the method to validate all instances of `Statemachine` as per the first argument of the method. The method is invoked for each `statemachine` instance in the model.
<2> Espilce Periksa provides a `ValidationLibrary` containing reusable validations, e.g. validating duplicates in feature values.
<3> The API of Espilce Periksa allows to easily report an `info`, `warning` or `error`.

Finally you need to register your model validations, such that they will be automatically invoked as part of validating each applicable model instance.
The easiest way to do this is by means of an extension point that is provided by Espilce Periksa, as per the example below.

.Registering validations in link:{giturl}/plugins/com.altran.ec.mde.skeleton.espilce.periksa/plugin.xml[plugin.xml^]
[source,xml]
----
include::{gitdir}/plugins/com.altran.ec.mde.skeleton.espilce.periksa/plugin.xml[]
----

=== Espilce Polvi

WARNING: TODO

=== Xtext/Sirius Integration

WARNING: TODO

=== Xtext Move Refactoring

WARNING: TODO



